# Site settings
title: Josh Rozner
description: > # this means to ignore newlines until "baseurl:"
  Josh Rozner's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jsrozner
github_url: "https://github.com/jsrozner"
facebook_username: jsrozner
facebook_url: "https://www.facebook.com/jsrozner"
linkedin_username: jsrozner
linkedin_url: "https://www.linkedin.com/in/jsrozner"

# Build settings
markdown: kramdown
